version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ports:
      - "9200:9200"
    volumes:
      - "./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    depends_on:
      - "elasticsearch"
    ports:
      - "5601:5601"
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
  gnatsd:
    image: nats
    command: -DV -m 8222 -l /tmp/nats.log
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
    volumes:
      - "./nats.log:/tmp/nats.log"
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.2.0
    depends_on:
      - "elasticsearch"
      - "kibana"
      - "gnatsd"
    command: ./start-filebeat.sh
    volumes:
      - "./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "./start-filebeat.sh:/usr/share/filebeat/start-filebeat.sh"
      - "./nats.log:/tmp/nats.log"
  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.2.0
    depends_on:
      - "elasticsearch"
      - "kibana"
      - "gnatsd"
    command: ./start-metricbeat.sh
    volumes:
      - "./metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro"
      - "./start-metricbeat.sh:/usr/share/metricbeat/start-metricbeat.sh"
